### ISSUE TITLE
Sync BME680 with pycom RTC

### ISSUE THREAD

**Issue by Arliom** [robert-hh/BME680-Micropython#4]
BME680 only works when the pycom RTC is not  updated
When the RTC is updated the pycom give this error:
> WLAN connection succeeded!
RTC Set from NTP to UTC: (2022, 2, 14, 17, 58, 13, 508646, None)
Traceback (most recent call last):
      File "main.py", line 47, in <module>
      File "main.py", line 29, in setSensorBME
      File "/flash/lib/bme680.py", line 187, in temperature
TypeError: unsupported types for __mul__: 'NoneType', 'int'

When RTC is not updated: 

> WLAN connection succeeded!
RTC Set from NTP to UTC: (1970, 1, 1, 0, 0, 13, 304882, None)
Temp:  22.10441  Hum:  50.05791  Press:  1024.178  AQI:  12.20809

This is the part of my code when I conect:
`rtc= RTC(id=0)
        while not wlan.isconnected():
            wlan.connect(ssid=self.a, auth=(network.WLAN.WPA2, self.b))
            time.sleep(2)
            print(wlan.ifconfig())
        print('WLAN connection succeeded!')
        rtc.ntp_sync("pool.ntp.org")
        time.sleep(2)
        print('RTC Set from NTP to UTC:', rtc.now())`

I tried to change sensor to SPI connection and gives the same error, I tried other pins, and print first the sensor, then the RTC, but it only give error when takes this structure RTC>BME680, I also used time.sleep() but still not works

**Comment by robert-hh** [comment]
Try changing line 132 from
`        self._last_reading = 0`
to
`        self._last_reading = time.ticks_ms()`

**Comment by Arliom** [comment]
It gives the same error

**Comment by robert-hh** [comment]
Then try replacing line 260 from 
`return`
to
`time.sleep_ms(self._min_refresh_time)`
The return there is the only reason why _t_fine may be not set.

**Comment by Arliom** [comment]
Now it gives me this error:

> Traceback (most recent call last):
      File "main.py", line 243, in <module>
      File "main.py", line 112, in setSensorBME
      File "/flash/lib/bme680.py", line 186, in temperature
      File "/flash/lib/bme680.py", line 260, in _perform_reading
TypeError: can't convert float to int

**Comment by robert-hh** [comment]
Then change additionally line 133 to:
`        self._min_refresh_time = 1000 // refresh_rate`
That make the result an int. Sorry, I have not BME680 here at the moment for testing myself.

**Comment by Arliom** [comment]
It works!, thank you so much for your support

**Comment by johnedstone** [comment]
Awesome!!
I have been struggling with this error for the last week, first trying to understand it, and then wondering why the return value of `self._t_fine` is None.  Why is updating RTC causing this error, do you know?

Here is what has worked for me [running from REPL](https://github.com/johnedstone/pycom-gpy/blob/17b9d6151024afb2d3699602c324491ec914fe05/simple_files/gps_bme680_test/lib/breadboard.py)

And [this script, which uses RTC ](https://github.com/johnedstone/pycom-gpy/blob/17b9d6151024afb2d3699602c324491ec914fe05/projects/post_json_data/main.py), fails at line 43, when bme680 is called after RTC is updated.

I'll implement your changes and let you know if this fixes it.  What do you think is going on?  It acts as if the bme object loses connection to the hardwar after RTC is updated.

**Comment by robert-hh** [comment]
The driver in the repository has been updated. So it should work.

The reason for RTC interfering with the BME680 driver is a little bit subtle.
The driver checks, that a certain time gap is kept between measurements and uses ticks_ms() for that. So it checks something like:
(now - previous) > min_time
ticks_ms() returns a 32bit signed integer and is based on the RTC, which is not common. If RTC is not set, the values start at 0. And the first value of previous was initialized to 0. So if you call for bme680 values not too late after boot (< 24 days), the value of (now - previous) is a positive number. If RTC is set, ticks_ms() may return a negative number, and then (now - previous) is negative, and a value of None is returned. So one of the changes was to set the start value of previous to the actual time. The other change was a float/int collision.

**Comment by johnedstone** [comment]
First, thanks for writing this driver, bme680.py.  It was something that I had been looking for.  And thanks, too, for this latest fix!! Thanks for the explanation as well, much appreciated. The driver, the latest version, has enabled me to to finish [this project of using a GPy, a PyTracker v2, and Adafruit's bme680 board to post data to a REST API.](https://github.com/johnedstone/pycom-gpy/tree/aa7acf27be2b0bbda655aa1e36e764b942979705/projects/post_json_data)
Here is a patch, a simple typo, for your latest commit of bme680.py
```
--- 3788dc4_bme680.py	2022-03-29 19:17:50.095847695 -0400
+++ updated_bme680.py	2022-03-29 19:19:25.868284570 -0400
@@ -257,7 +257,7 @@
            calculations"""
         expired = time.ticks_diff(self._last_reading, time.ticks_ms()) * time.ticks_diff(0, 1)
         if 0 <= expired < self._min_refresh_time:
-            time_sleep_ms(self._min_refresh_time - expired)
+            time.sleep_ms(self._min_refresh_time - expired)
 
         # set filter
         self._write(_BME680_REG_CONFIG, [self._filter << 2])
```

**Comment by robert-hh** [comment]
Thank. I fixed it.
