### ISSUE TITLE
improving accuracy calcuation, with Bosch's formula

### ISSUE THREAD

**Issue by bradcar** [robert-hh/BME680-Micropython#5]
In your code for altitude you have 
return 44330 * (1.0 - math.pow(pressure / self.sea_level_pressure, 0.1903)) 
In the Bosch Sensor guide (ex: in bmp180 they show a different formula page 16 of: https://cdn-shop.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf). 
Since you are raising the difference  in pressure & SLP to a power, then small differences can make a difference.

Consider this return value instead:
return 44330 * (1.0 - math.pow(pressure / self.sea_level_pressure, (1.0 / 5.255)))

Or if you want to not divide,  fp32 has 6-9 digits of accuracy, so you could pre-calculate.
return 44330 * (1.0 - math.pow(pressure / self.sea_level_pressure, 0.190294957))

Generally But I find it best to stick to letting the divider keep things full accuracy, so I’d suggest (1.0 / 5.255)

**Comment by robert-hh** [comment]
Hi Brad. Thank you for your comment. This can be done, following the data sheet. But I do not expect a substantial change. The resulting number will be slightly different, smaller than the error of the sensor. 
I do not know if the number 5.255 is precise or some rounded quantity. I assume the latter.

**Comment by bradcar** [comment]
your choice of course.   The more important thing is for people to set the nearest sea level pressure (airport) at local time, or set the altitude to set the sea level pressure.

BTW, in my searching I found a more authoritative source: 
NSF's NCAR formula: https://ncar.github.io/aircraft_ProcessingAlgorithms/www/PressureAltitude.pdf

**Comment by robert-hh** [comment]
Thank you for the reference to the NCAR document. We could use the numbers from this paper.

**Comment by bradcar** [comment]
I think of it this way, you are right the bme680 isn't that accurate, but compounding that with an altitude calculation errors doesn't help things.

The NCAR formula just has different constants.  If we ever get newer generation bmexxx that you want to adapt your driver to, then you know that altitude calculation is correct.

I'm using your driver in a couple of personal projects, but it is just as easy for me to just get the pressure of this and other sensors and do the calculations with my own formula based on NCAR.

**Comment by robert-hh** [comment]
I already updated the repository using the constants the NCAR document suggests, of course mentioning you and your help.
