### ISSUE TITLE
IAQ

### ISSUE THREAD

**Issue by bradcar** [robert-hh/BME680-Micropython#7]
<<<EDITED 12/10/2024 - do not use the formula in italics below, it is wrong>>>
_if you want, one thing that is often defined is something called "Indoor Air Quality"
  gas_kohms = bme.gas / 100
  iaq_value = log(gas_kohms) + 0.04 * percent_humidity_

Typical values for IAQ
    IAQ: (0- 50 low, 51-100 ave, 101-150 poor, 151-200 bad, 201-300 Very Bad, 301-500 dangerous)

**Comment by robert-hh** [comment]
This part of the driver was still due and an open ToDo for me. Thank you for the reference. Do you have a link to a document or source about the above formula? See issue #3.

**Comment by bradcar** [comment]
This is a reference, I thought I had another one, but can't find it now.  Do you want me to do pull request to implement or would you rather just do it?

https://github.com/thstielow/raspi-bme680-iaq

**Comment by bradcar** [comment]
there is this discussion as well: https://forums.raspberrypi.com/viewtopic.php?t=293793

**Comment by robert-hh** [comment]
I#d be happy if you make a PR for it. Do you have a means to test it?

**Comment by bradcar** [comment]
Yes I can make a PR & test later this week.

**Comment by bradcar** [comment]
May take more than a week...

**Comment by robert-hh** [comment]
Take your time. That topic has been due for a while.

**Comment by bradcar** [comment]
An update: I can see why you punted on this issue, clearly you understand the confusion in the area more than I did. 

There are various calculations by a different people
For example David Bird in 2019 has this code: 
https://github.com/G6EJD/BME680-Example/blob/master/ESP32_bme680_CC_demo_03.ino#L34. it plots out like this:
![david-bird-plot](https://github.com/user-attachments/assets/41d7fa45-3e9b-419d-8ce1-ee5d9cc5f194)

**Comment by bradcar** [comment]
at: https://forums.pimoroni.com/t/bme680-observed-gas-ohms-readings/6608
skypi Paul Rogers shared this:
_"so I doubt these are ‘ohms’ readings, the tests were with standard pimoroni library and the read-all example modified to log in a csv friendly format."_

_based on about 30mb of readings over few days_

_521177 - 431331 - good?
297625 - 213212 - average ?
148977 - 108042 - little bad ?
75010 - 54586 - bad ?
37395 - 27080 - worse ?
18761 - 13591 - very bad ?
9008 - 8371 - can’t see the exit ?_

**Comment by bradcar** [comment]
at: https://github.com/thstielow/raspi-bme680-iaq/blob/main/bme680IAQ.py
thstielow  code at a temp of 25c has this plot:
![thstielow2](https://github.com/user-attachments/assets/f5d7bbe7-ff08-4264-96b8-64bc83e57a5c)

at: 
https://github.com/zangaby/ESP8266_BME680_air_quality/blob/main/ESP8266_BME680.ino

![zanaby](https://github.com/user-attachments/assets/a3346052-37b1-42ca-a8cd-6e87eb7a64aa)

**Comment by bradcar** [comment]
Hi Robert, I'm going to bail on this effort.I don't feel I can find the right code, or the proper data to create the code. 

It'd be interesting to see the Bosch algorithm IAQ plot on gas resistance, humidity, and temp, but that is likely prohibited by licensing. Bosch makes some great sensors, but I think they got greedy with their SW.

There also may be other sensors to look at: 
https://pmc.ncbi.nlm.nih.gov/articles/PMC11054856/

**Comment by bradcar** [comment]
This sensor looks interesting for people wanting to accurately read multiple chemicals:
The MiCS-6814
https://www.sgxsensortech.com/content/uploads/2015/02/1143_Datasheet-MiCS-6814-rev-8.pdf
and this one:
MICS-5524 Gas Sensor for CO Natural Gas Leakage Detection Alcohol VOC NH3 Methane Gas Sensor Breakout Board

If the Bosch leaders hadn't made the decision to close the software, I never would have found this great line of sensors made by SGX :)

...sorry Robert, but I'm done with this for now, you can close this.

**Comment by robert-hh** [comment]
Thanks for the link to the MiCS sensor. It looks good.
I considered for a  while to reverse engineer the Bosch driver. As far as I understood the operation, the resistance has to be measured at different temperatures, which then gives some information about gases. But without a suitable documentation this is just guessing. Not to speak about verification tests.
Ok. I'll close this. If you have a driver for the MiCS chip, please publish it.

**Comment by bradcar** [comment]
This reference may be useful for someone:
https://assets-global.website-files.com/61822390f9078179b84556a4/61afdba10a1d06c4ae089dc4_IAQ_Rating_Index.pdf

**Comment by bradcar** [comment]
Looking an the various data sources, I came up with my own formula, but I have not vetted this with any experimentation. You can see the code in my method: def calculate_iaq(gas_ohms, percent_humidity) at: 
https://github.com/bradcar/digital-altimeter-rp2/blob/main/altimeter-digital-rp2.py

It is limited by only using gas ohms and humidity at one moment in time. I wouldn't trust it for accuracy, but it is good enough for my casual use and is relatively simple to calculate. Here is the 3D plot of the IAQ surface:
![mycalc](https://github.com/user-attachments/assets/ae63ec33-8d75-4688-85fa-d4b7dd87a341)

BTW, sorry that the axes in all of the graphs are different, so pay attention if you are trying to compare them.
